import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface': '#1b1c1c',
        'surface-dim': '#dbdad9',
        primary: '#b51b17',
        'primary-fixed': '#ffdad5',
        tertiary: '#006480',
        background: '#fbf9f9',
        'on-tertiary-fixed-variant': '#004d64',
        outline: '#8f706b',
        'inverse-on-surface': '#f2f0f0',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1b1c1c',
        'inverse-primary': '#ffb4aa',
        'secondary-container': '#e2dfde',
        'surface-tint': '#b91e19',
        'primary-fixed-dim': '#ffb4aa',
        error: '#ba1a1a',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#74d2f9',
        'secondary-fixed': '#e5e2e1',
        'primary-container': '#d9372d',
        'inverse-surface': '#303031',
        'on-secondary-fixed-variant': '#474746',
        'surface-container-low': '#f5f3f3',
        surface: '#fbf9f9',
        'on-primary-fixed-variant': '#930006',
        'on-error': '#ffffff',
        'on-secondary-container': '#636262',
        'on-primary-fixed': '#410001',
        'on-tertiary-container': '#fbfdff',
        'on-secondary': '#ffffff',
        'on-primary-container': '#fffbff',
        'error-container': '#ffdad6',
        'on-background': '#1b1c1c',
        'surface-container-highest': '#e3e2e2',
        'surface-bright': '#fbf9f9',
        'tertiary-container': '#007ea1',
        'tertiary-fixed': '#bce9ff',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#001f2a',
        'on-surface-variant': '#5b403c',
        secondary: '#5f5e5e',
        'outline-variant': '#e4beb9',
        'surface-variant': '#e3e2e2',
        'surface-container': '#efeded',
        'surface-container-high': '#e9e8e7',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Lexend', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
